### ISSUE TITLE
Docker improvements

### ISSUE THREAD

**Issue by zais** [izderadicka/audioserve#1]
Hello, i think docker image can be better if:

1. Accessible from hub.docker.com
2. Provides parameters for enable/disable https, enable/disable passkey, set custom passkey

Hope project is not dead

**Comment by izderadicka** [comment]
No project is not dead - I'm using it on daily basis, plus recently updated to new tokio/hyper.
Current docker image was intended mainly for initial testing. 
Are you willing to submit PR improvements for Dockerfile?
I think one more improvement for docker could be to enable to use several audio folders (as audioserve enables that).
After improvement I can push image to my docker.hub account.

**Comment by zais** [comment]
I'm lacking Docker knowledge to implement that, unfortunately :(

**Comment by mpatton125** [comment]
Hey there,

Just discovered audioserve today while looking for something simple that works.  This is it! :)
I have some Docker experience and would love to provide any assistance I can to help this project along.

I will take a look into providing the above and will submit a PR when I have something.

**Comment by izderadicka** [comment]
Docker file improved with env variables thanks to @mpatton125
