### ISSUE TITLE
Secret not working and Android unable to connect

### ISSUE THREAD

**Issue by danfickling** [izderadicka/audioserve#12]
Firstly, I really like what's being done with this tool, and especially the app. If I can get it up and running I think it'll be perfect for me. So, thanks for making it!

My setup is running in docker with a reverse proxy, which works fine to serve up the site, but the shared secret seems to be ignored entirely. The audioserve.secret key is being created and there is nothing in the logs to indicate any issues.

I tried opening the port to the web and it still ignores the shared secret so it seems like it's not an issue with the reverse proxy.

Additionally, and perhaps this is somewhat unrelated, when trying to connect to the server through the Android app I get a generic server error message, whether or not I have set a shared secret.

If I go to the site to test out the response from the API manually, I get expected responses except where I go to /authentication and simply get 'Not Found'.

As an aside it would be super useful to serve the API requests from a shared sub-directory such as /api so I could easily add different auth settings for the API. :)

**Comment by danfickling** [comment]
I just noticed in the docs it says 
`
-e AUDIOSERVE_SHARED_SECRET=mypass \
    audioserve \
    --ssl-key /audioserve/ssl/audioserve.p12 --ssl-key-password mypass \
`

Are those two instances of mypass linked? I'm wondering if that's my problem as I haven't specified the ssl-key or ssl-key-password. Since I'm using a reverse proxy I'm not sure how I would set these anyway?

**Comment by izderadicka** [comment]
Few thing:
-  by default docker image is not using authentication (see Dockerfile), so for authentication to work you need to supply shared secret via -s argument or env.variable 
-  in web client you can easily see what's going on in web developer tool - network. Delete cookie to force new authentication 
-  concerning android some people have problems with clear http, try setup https with real certificate on your reverse proxy.
-  re: aside API - There is only one API which is serving everything - web client, android client and also available per se.
-  shared secret and ssl key password  are not related - in example they just happen to be same. You can enable tls/ssl in audioserve, but I and most people are using reverse proxy for ssl termination.

Hope you will succeed in your setup, if any further problems let me know.

**Comment by izderadicka** [comment]
where I go to /authentication and simply get 'Not Found'.


Authentication endpoint should be /authenticate

**Comment by danfickling** [comment]
Thanks for the feedback.

I've actually set the environment variable already. It's in the code I posted above.

My reverse proxy is also using letsencrypt, so shouldn't be any issues within Android not accepting it.

I also tried accessing in an incognito tab and it didn't ask for the secret, which I would expect of it was a cookie issue.

I didn't think the SSL settings were necessary for me but the same password threw me a bit. Good to get that cleared.

My point about the API was just around being able to easily provide different auth requirements based on URL structure. Come to think of it though, it probably wouldn't make a difference in practice because I assume streaming the audio files is still done through the same URL as the web server. i.e. not accessing from an API specific URL.

**Comment by danfickling** [comment]
So I just tested the exposed port through direct IP connection on the app and I still get the same 'Connection error: Server' message. Nothing in the logs to indicate that a connection attempt was made either. Tested with the shared secret set and also unset. Same problem.

As an aside, no cookies seem to have been set in my browser either.

Additionally, if I don't set a shared secret, the app still seems to recreate a audioserve.secret file.

**Comment by danfickling** [comment]
So this is interesting. If I run it via command line like so, it works, and it asks for the shared secret:

`
docker run -d --name audioserve-test -p 3000:3000 -e AUDIOSERVE_SHARED_SECRET=mypass -v /audioserve:/home/audioserve/.audioserve -v /audiobooks:/audiobooks  izderadicka/audioserve /audiobooks
`

So it definitely seems to be an issue with running the container through docker-compose.

I'm going to test to see if the YAML config approach will work while being initiated through docker-compose.

**Comment by danfickling** [comment]
So I've done some more testing with a YAML file, using the exact one that was spat out from the command above that worked. Unfortunately It isn't working when run from docker-compose. It's definitely reading from the file though.

I'm starting to wonder if, using docker-compose, somehow it's setting the 'no-authentication' flag. That would explain why it's just completely ignoring having authentication set. Unfortunately I can't see a way to unset it. There's not like a 'no-authentication=false' is there? I have no idea how docker-compose is behaving differently from the command line though.

```
    if args.is_present("no-authentication") {
        config.shared_secret = None;
        no_authentication_confirmed = true
    } else if let Some(secret) = args.value_of("shared-secret") {
        config.shared_secret = Some(secret.into())
    } else if let Some(file) = args.value_of_os("shared-secret-file") {
        config.set_shared_secret_from_file(file)?
    };
```

**Comment by izderadicka** [comment]
Only if --no-authentication is provided explicitly them authentication is switched off. Otherwise some form of shared secret must be provided or program exits with non zero return code.
The --no-authentication is in default CMD in Dockerfile, so this might be the way how it sneaks in. I never tried with docker-compose, just directly with docker. Can you share your docker-compose yaml, I'll try next week when I'm back home.
Also I think Android client is always trying to authenticate, so that can be reason why it is not working, so be sure authentication is working before trying Android. --no-authentication is for testing purposes only, I think I should not have it in Dockerfile as default, try change Dockerfile? Maybe it's overwrites env.var in docker-compose?

**Comment by izderadicka** [comment]
Command line arguments have precedence over env.vars. So compose must be using default CMD from Dockerfile. Try to set there other CMD ( command here are parameters to audioserve)

**Comment by danfickling** [comment]
haha, I just tried that exact thing and it worked!

So here's the line that's needed in docker-compose to make it work:
`command: /audiobooks`

That's it. All working now. Even Android's happy now :)

**Comment by izderadicka** [comment]
Good, closing issue.

**Comment by ChiefMedicalOfficer** [comment]
> 
> 
> haha, I just tried that exact thing and it worked!
> 
> So here's the line that's needed in docker-compose to make it work:
> `command: /audiobooks`
> 
> That's it. All working now. Even Android's happy now :)

Hi there. Where exactly did you input the above into your compose file? I can get everything to work from 'docker run' but the compose setup is eluding me.

Thanks.

**Comment by izderadicka** [comment]
It depends on what you want - if you need authentication by shared secret then I'd put

```yaml
command: /audiobooks  #this should be your mounted directory with audiobooks
environment:
    AUDIOSERVE_SHARED_SECRET: mypass
```

or you can put shared secret in commend (less secure)
```yaml
command: ["-s", "mypass", "/audiobooks"]
```

**Comment by ChiefMedicalOfficer** [comment]
Thanks. I'll give this a try.
