### ISSUE TITLE
Enhacement, KISS: m4b alone in a dir should not be interpreted as a nested directory.

### ISSUE THREAD

**Issue by BansheeHero** [izderadicka/audioserve#14]
- Containers and directories serve similar purpose as folders.
 - Nesting the chapters into another directory serves little purpose as the mission statement is to use folders anyway.

I think that combined with KISS should lead to ignoring the extra level.

**Comment by izderadicka** [comment]
I see, makes  sense, but can get complicated on server side logic, now it's rather simple - any entry in directory structure is either directory (true directory or container) or media file. With proposed approach we will need to check, that if directory entry has only one child and it's container then collapse one level. 
And there is also a corner case - directory of author with one m4b file -   Smith John/Great Book.m4b - if we follow proposed approach then chapters will be directly under Smith John folder, which is probably not the desired outcome.  
As per now it's left to user - they generally should not create an extra folder for containerized audiobook (but they can if they want), I think this way it's more simple (at least from implementation perspective).

**Comment by BansheeHero** [comment]
I see, I generally use folder and m4b since not all players treat m4b differently than single file.
In fact this is the first time I saw m4b being treated this way.

I do understand the difficulty implementing such a corner case.

**Comment by izderadicka** [comment]
Implemented in current  master branch- if the only audio content of directory is one m4b file its chapters are displayed directly in that folder.  Actually I think this way you proposed is better (after having some m4b in my collection), it will enable to add cover and description to directory, plus search will work on dir name.  If people like the old way these is an option `--no-dir-collaps` to switch it off.
