### ISSUE TITLE
iOS devices - playback error

### ISSUE THREAD

**Issue by paulmorabito** [izderadicka/audioserve#17]
Hi,

I'm trying to access AudioServe using iOS Safari on a 2017 IPad (latest iOS release) and get a playback error. The logs in docker show this, though I am not sure it's directly related:

WARN  audioserve::services::transcode > Transconding of file "/audiobooks/file.mp3" failed with code Some(1)

The same file plays on android and MacOS desktop as well as Windows.

Any help would be very appreciated.

**Comment by izderadicka** [comment]
Problem here might be that audioserve is transcoding using default profile - which is Opus codec in Ogg container.  I'm not sure how/if Safari on IPad can handle this (if not it will close the stream and this can cause to transcoding error). 
I would recommend to switch transcoding completely off in client - (in top right menu) - this will send file unchanged.

Officially I do support only Firefox and Chrome on Linux and have no plans to extend to Apple world, as I do not have their products.

I do not know if there is some remote web developer console for Safari (like there is one for Chrome, FF), but you can try it to see log and what Safari is complaining about.

If this is the issue you can then try to play with transcoding formats in audioserve config file, there are also other formats available, but I do have best experiences with opus and ogg in Firefox.

**Comment by paulmorabito** [comment]
Thanks for replying. I've tried to access the menu to disable transcoding
in Safari and Chrome on iOS but it doesn't appear.Also tried loading
desktop site and it had no effect. I agree it is definitely the codec not
being supported. Is there a way to disable transcoding any other way or to
make a profile for certain user agents?

**Comment by izderadicka** [comment]
There is no per device specific transcoding (only three profiles low, medium, high from which you can choose on client). It's strange that Chrome does not show the menu button (three vertical dots on top right).  I'm using bootstrap CSS framework, which should be pretty much standard). 
To test you can try to modify mediu transcoding profile (which is default for client) to some high kbps value - thus there will not be any transcoding).

**Comment by izderadicka** [comment]
Any update? 
I tried on browserstack.com on remote iOS device - can confirm that menu is not shown on click in Safari,
but do not know exactly why, cannot get much details there.

I use standard bootstrap 4 dropdown menu.  
Looking a bit over internet I found this: https://stackoverflow.com/a/25760476/1720030

I'll try to add the style, as it would be good to have pointer cursor over menu button anyhow.

**Comment by paulmorabito** [comment]
No major update. I tried various transcoding profiles with mixed success.

Let me know if you update. More than happy to re-test.

**Comment by izderadicka** [comment]
Surprisingly enough previous tip did worked - just adding CSS pointer cursor on menu button made it work on iOS - quite weird.
Latest version 0.11.3 is in master (and soon released) - you can test it also online here https://audioserve.herokuapp.com/ (just wait a bit for heroku to load image) - password is mypass .  Now you can disable transcoding in menu and mp3 should work (at leas.  As already noted default transcoding is to opus, which has problems on iOS. But you can create custom configuration and use different transcoding (mp3, aac).

**Comment by bablat** [comment]
Hello @izderadicka,

I'm trying to use the docker version, right now I'm on the latest image and seeing this issue when accessing from my latest version iOS device.
Here is the relevant log data:

```
[2021-02-14T22:01:35Z ERROR audioserve::services] Invalid path requested /favicon.ico
av_interleaved_write_frame(): Broken pipe
Error writing trailer of pipe:1: Broken pipe
[2021-02-14T22:02:35Z WARN  audioserve::services::transcode] Transconding of file "/audiobooks/[removed]" failed with code Some(1)

```

**Comment by izderadicka** [comment]
@bablat  - try without transcoding first -  opus + ogg have problem with Safari.   If transcoding is needed try other settings then opus - mp3 to start with.

**Comment by bablat** [comment]
> @bablat  - try without transcoding first -  opus + ogg have problem with Safari.   If transcoding is needed try other settings then opus - mp3 to start with.

Thanks, disabling transcoding works. I suggest that you disable transcoding altogether on iOS by UseAgent string, or otherwise allow to completely disable transcoding globally, from the configuration.

**Comment by izderadicka** [comment]
@bablat transconding is decided at client - client can decide if wants to load transcoded or original file.   On server you set 3 transcoding profiles from which client can choose - high, medium, low - bit these are just names - you can setup in configuration any supported parameters you want -  so low can be MP3 for compatibility,  medium and high opus.  Audioserve is much about transcoding, without it's just simple web server with directory listing.

I think possibility to easily change transcoding in web client is enough.  Maybe browser detection JS can set no transcoding option as default for Safari .

**Comment by bablat** [comment]
Appreciate the response, I realize transcoding may be relevant to some,
however for me the main use case is simply playing audio books on my LAN.

As no transcoding is supported on Apple devices, I think that a JavaScript
detection function that disables transcoding for these devices would be
great, the current default simply doesn’t work.

Also, catching this error on server side and producing more relevant output
should help (“error transcoding, try disabling transcoding on client side
if you’re using an iOS device.”)

These are very common devices and most users would never figure it out
themselves. It’s a serious usability issue.

**Comment by izderadicka** [comment]
Added some simple check for IPhone and IPad to Web client - this will choose no transcoding by default for these platforms.
