### ISSUE TITLE
iOS and OSX+Safari do not support opus+ogg audio format

### ISSUE THREAD

**Issue by izderadicka** [izderadicka/audioserve#18]
Apple platforms do not support opus+ogg format, which is default in audioserve.  
On OSX alternative browser(FF or Chrome) seems to work fine, but Safari is not.

I think Apple supports opus, but only in matroska container, which does not work well with on-flow transcoding (as it requires seek access to stream to update header).

I think we should provide alternative configuration for apple platforms - probably aac codec?  
As I'm not using Apple, I'm just opening this issue if somebody has more experiences (and it would not be any problem to add additional transcoding configurations, provided it's supported by ffmpeg).

@paulmorabito - what transcodings  did work for you on iOS?

**Comment by paulmorabito** [comment]
I'll give your update a try and let you know how it goes on iOS.

About transcoding, mp3 seemed to work the best but I only tested it playing
and not much more.

**Comment by AnthumChris** [comment]
Ogg Opus files are supported on Safari with WebAssembly decoding:

- https://fetch-stream-audio.anthum.com/
- https://github.com/AnthumChris/fetch-stream-audio

**Comment by izderadicka** [comment]
With selective transcoding based on User-Agent string we can provide now alternative transcoding  to aac in ADTS for Apple agents.
