### ISSUE TITLE
ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by joemarshalljm** [izderadicka/audioserve#2]
I've installed the docker, ran the command but when I try and access my server on port 3000 I get "This site can’t be reached" - what could I be doing wrong?

When I run "docker ps" I can see that audioserve IS running on port 3000

**Comment by izderadicka** [comment]
Not sure, provided docker image is working for me,
try:
`docker run -it --name audioserve -p 3000:3000 -v /home/ivan/tmp/test_audiobooks/:/audiobooks -e RUST_LOG=audioserve=debug audioserve`
eg. to run with interactive console and debug log if there is anything.

But I think it's rather your docker issue - try another image - like httpd:
`docker run -it --name my-apache-app -p 8080:80 -v "$PWD":/usr/local/apache2/htdocs/ httpd:2.4`

Check if port 3000 is free.

Provide more details on your environment OS, docker version.

**Comment by izderadicka** [comment]
Any update? Otherwise I'll  close because it's probably  your local Docker issue.

**Comment by joemarshalljm** [comment]
I think it's because I don't have the SSL.

How to I run with no default features? I see in the readme about adding the flag to 'cargo' but I have no idea what that means!

**Comment by joemarshalljm** [comment]
edit: I think I'm an idiot, I just needed to go to https:// rather than http://

But now I'm not sure how to get the Android app to work, I'm getting a network error

**Comment by izderadicka** [comment]
Yes, but should include trailing slash, so for instance if you are connecting from emulated Android to audioserve on localhost then it's http://10.0.2.2:3000/    (on emulators local subnet)
