### ISSUE TITLE
Websocket errors in error logs

### ISSUE THREAD

**Issue by Mange** [izderadicka/audioserve#20]
My logs are full of these messages:

```
 ERROR websock > Upgrade is not to websocket
 ERROR websock > It must be upgrade connection
```

I'm running audiosurf behind an nginx proxy. Do I need to do something special to get WS to work behind there?
I'm on HTTPS-only.

---

_Originally posted by @Mange in https://github.com/izderadicka/audioserve/issues/16#issuecomment-525442375_

**Comment by izderadicka** [comment]
My nginx configuration is 
```
location /audioserve/ {
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Host  $http_host;
        proxy_set_header Host              $http_host;
        proxy_max_temp_file_size           0;
        proxy_pass                         http://127.0.0.1:3000/;
        proxy_redirect                     http:// https://;
        proxy_read_timeout 1200s;
        send_timeout 1200s;
        }

   location /audioserve/position {
      proxy_pass http://localhost:3000/position;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_read_timeout 3600s;
        }
```

**Comment by izderadicka** [comment]
And I'm getting different errors

    ERROR websock                                       > Socket error Ws

But I think it's kind of legitimate, it happens when websocket gets disconnected.

@Mange  - in your case looks like websocket is not established at all so I guess position sharing will not work at all?

**Comment by Mange** [comment]
That seems to have made it work. Now the socket is established and Chrome's websocket sniffer shows messages being passed on it.

However, I cannot tell a difference from before. What will it do?

Opening the same directory in a different client does not show the current file, and starting the file won't jump the the position that was paused on the other device. Having both devices open at the same time does not show the position getting synced, either.

What behavior should I expect to tell if this is working or not?

---

All three devices (Firefox, Chrome, Android app) are using the same Group name.

**Comment by izderadicka** [comment]
first both devices must have same group in their setup.
next play for a while on one device.
On other device - either

a) Click play on opened file (file must be already in progress, paused), if there is newer position from other device is available, then dialog show offering you to got to that position, or continue with current file. If there is no more recent position, playback will just continue. 

b) On device - in folder choose to show most recent positions ( icon of triangle with circle arrows, or in Android in 3 dot menu Check remote positions (also in Recently played, most recent remote position can be shown, if newer then local positions).

Playback position on other device must be at least 10 secs from current position to be considered different. 

Also this functionality is not about  parallel  playback on several devices- it's about pausing playback on one device and continue on other device.

As I have written it's experimental, so any feedback on this functionality is welcomed. There is special issue for this #6 .  My experience so far is that it somehow works, but is not very reliable.

**Comment by Mange** [comment]
Thanks! I didn't get that behavior from what I could tell, but I'll make sure to experiment more later. I'm on my way to the airport for a family vacation, so I'll be on a single device for now.

In either case, it seems the socket connection works now so I'll close this issue. Thank you for your help!
