### ISSUE TITLE
Users? Or multiple secrets & associate bookmarks to them?

### ISSUE THREAD

**Issue by Naenyn** [izderadicka/audioserve#24]
First off, fantastic project! This is almost exactly what I’ve been looking for. One issue... users. I respect that there is a desire to keep things simple and just use one secret. However, if I share my library with my family, bookmarks are going to get jumbled up. How about having multiple secrets and associating bookmarks with a secret? Or perhaps a simple user,pass csv file? It would be nice if the small number of users I’d grant access to the server would each have their own bookmarks.

**Comment by izderadicka** [comment]
Actually bookmarks are not kept on server - so they cannot get jumbled. 
If you are speaking about bookmarks in Android client - they are kept locally in device -  stupid but simple.

Having server to maintain bookmarks would be useful indeed  - but not priority now. (Priority is #23 )

**Comment by Naenyn** [comment]
Ahh! I hadn't realized bookmarks were clientside. So, that means switching from the android client to the web client would cause the user to lose their place. Yeah, I definitely vote for server side bookmarks then. =]

Thanks for the response!

**Comment by izderadicka** [comment]
Actually there is kind of experimental playback continuation  on different device- see in readme. There you define so called devices group - so it can work for multiple users.  It somehow works, but it's not totally reliable.

**Comment by izderadicka** [comment]
After updating to new collection cache we still using group concept, which enables to share last position for any folder within given group. I hope it solves main use case. There are plans to have multi user system, you always share collections, just can define groups that share playback positions.
