### ISSUE TITLE
Feature request: similar functionality for MP4 / AVI video files

### ISSUE THREAD

**Issue by Bougakov** [izderadicka/audioserve#29]
Audioserve is very helpful for listening to audiobooks hosted on a local file server.

But in addition to the audiobooks I have lots of educational courses in MP4 or AVI format. They are also organized in folders, such as `Topic 03 / Chapter 11.mp4`

I'd be extremely happy if I could watch those courses in a browser in a similar manner. Can you please add support for streaming them directly, without transcoding? I presume that the required changes are minimal and require only adding a JavaScript video player to the client, such as https://plyr.io/, https://videojs.com/ or http://jplayer.org/ Thanks in advance.

**Comment by izderadicka** [comment]
On my side there are no plans for video support

**Comment by wtanksleyjr** [comment]
It does seem like a brilliant and simple setup, but if you look at media
players, you'll find that when they try to add support for audiobooks they
have (so far) failed badly. It's probably not a good bet to try to make
working the other way work well.

However, you might be interested in media player servers like Jellyfin,
Emby, and Plex.

-Wm

**Comment by Bougakov** [comment]
> However, you might be interested in media player servers like Jellyfin,
Emby, and Plex.

Sadly, my file server is an old machine with an Atom processor. Apps like Plex are too much for it. Also, **all the media servers rely on tags**, whilst **video courses are folder-based**, just as audiobooks.

**Comment by wtanksleyjr** [comment]
Your machine definitely cannot transcode, but if it can't run Plex without
transcoding it won't be able to stream at all. And although I don't know
Emby and Jellyfin, I would be surprised if they didn't support the "no
tags" type of media library, based only on folder name.

**Comment by izderadicka** [comment]
Giving it second thought,  I do not think it's good idea to add video support.  Main design goal around audioserve was KISS - Keep It Simple Stupid  -   adding videos will add another level of complexity (additional formats,  video vs audio player, support in android etc.), which I'd like to prevent - let just keep it to do one thing good - serving audio files from directories with efficient and quality transcoding (e.g opus).  For more complex media servers go elsewhere  as suggested above (but neither plex, nor Emby are open source)
