### ISSUE TITLE
Spacebar pause/play

### ISSUE THREAD

**Issue by Phytophthora** [izderadicka/audioserve#30]
It would be nice to be able to use the spacebar as shortcut to play and pause the audiobook in the web client.

**Comment by izderadicka** [comment]
Agree, I think this would not be difficult - it concern just Javascript.

**Comment by Phytophthora** [comment]
Adding the following to main.js works if you add tabindex to .audio-player.
The getKeyFunction could be used to add some more keys eg. arrow keys to forward/rewind
Also adds focus to the player.
Don't know if it's a nice solution though and the right place to add to.

```
function getKeyFunction(event){
    if (event.keyCode === 32) {
        player.togglePlay();
    }
}
```
`$("#player .audio-player").focus();`
`$("#player .audio-player").on('keydown', getKeyFunction);`

**Comment by izderadicka** [comment]
Added to latest version - actually it was easier to emit click on play-pause button (as there are some other code bind to click). Seems that is works mostly OK.  
Approach with focus will not work if user clicks somewhere else and focus will move to other element.
