### ISSUE TITLE
Build fails without feature folder-download

### ISSUE THREAD

**Issue by mverboom** [izderadicka/audioserve#318]
Hi,

I always build audioserve from source code. Recently builds have been failing. I finally found out what causes the issue.
When building without feature folder-download there is an error triggered by the return part in "src/services/mod.rs"

```
                        #[cfg(not(feature = "folder-download"))]
                        {
                            error!("folder download not ");
                            response::fut(response::not_found)
                        }
```

The error is:

```
error[E0308]: mismatched types
   --> src/services/mod.rs:385:29
    |
264 |     ) -> ResponseResult {
    |          -------------- expected `std::result::Result<Response<http_body_util::combinators::box_body::BoxBody<bytes::Bytes, std::io::Error>>, anyhow::Error>` because of return type
...
385 |                             response::fut(response::not_found)
    |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `Result<Response<...>, ...>`, found `Pin<Box<...>>`
    |
    = note: expected enum `std::result::Result<Response<http_body_util::combinators::box_body::BoxBody<bytes::Bytes, std::io::Error>>, anyhow::Error>`
             found struct `Pin<Box<dyn Future<Output = Result<Response<BoxBody<Bytes, ...>>, ...>> + Send>>`
    = note: the full type name has been written to '/tmp/build/audioserve/target/release/deps/audioserve-fe4f3a079945ee8c.long-type-11147938523198805350.txt'
    = note: consider using `--verbose` to print the full type name to the console
```

Not a big issue, but I'd thought I would mention it :)

Thanks for the great application!!

Regards,

Mark

**Comment by izderadicka** [comment]
Hi,
I have done some refactoring in near past, but I think this is already fixed in master branch - see https://github.com/izderadicka/audioserve/blob/1ea213bfe8bd74347b70f81cf264761187cc51df/src/services/mod.rs#L382

I've done clean clone of master and `cargo check --no-default-features` passes.

Can you please assure you have assure you have latest master branch?
If there is still problem, please let me know.

**Comment by mverboom** [comment]
Oooh, doh.. Sorry, the build uses the latest tagged release. Works fine in master!

**Comment by izderadicka** [comment]
@mverboom  NP - thanks for letting me know - I will do some better release in future.
