### ISSUE TITLE
favicon for web client

### ISSUE THREAD

**Issue by Phytophthora** [izderadicka/audioserve#32]
Browser seems to try to load favicon by default from http://audiobook:3000/favicon.ico which is obviously not there.
![image](https://user-images.githubusercontent.com/8781818/85942488-db2a4680-b929-11ea-9b71-4e931a16e71b.png)

**Comment by izderadicka** [comment]
Yes, we do not have favicon and its normal behaviour of an browser to try to download  favicon, when it moves to new host.
