### ISSUE TITLE
Feature Request: Dark theme & cover view

### ISSUE THREAD

**Issue by limitlessbritt** [izderadicka/audioserve#34]
Hey, great work on this project, loving it so far! It Would be nice to have a dark theme option. Also it would be nice to have the option to display the cover images if there is one present in the directory instead of the directory name. Cheers!

**Comment by izderadicka** [comment]
@limitlessbritt  is it for web client or android? If for android it'll be better to log into it's own repo https://github.com/izderadicka/audioserve-android

**Comment by limitlessbritt** [comment]
Its for both so I will also open this issue in the android repo, cheers!

**Comment by methanoid** [comment]
I'd also like these enhancements.... (for both)

**Comment by izderadicka** [comment]
Dark theme is now available on new web client.

**Comment by izderadicka** [comment]
Replacing with #83 for remaining issue of cover images
