### ISSUE TITLE
Playback speed

### ISSUE THREAD

**Issue by gwenvador** [izderadicka/audioserve#35]
It would be nice to have the ability to set the playback speed per audiobooks. I like to listen at faster speed than 1x.

**Comment by izderadicka** [comment]
Playback speed and pitch is adjustable now only in android client. On Web client it'll require to add some control for `playbackRate` rate property of audio element.

**Comment by gwenvador** [comment]
I found it on the android app. For the web client that would be a great option if activated.

**Comment by kahnwong** [comment]
I use [this userscript](https://greasyfork.org/en/scripts/390508-html5-audio-video-keyboard-shortcuts-with-osd) to enable universal web player playback speed control. But it would be great if this feature is built in

**Comment by izderadicka** [comment]
Playback speed button added to Web client - with v0.15.1.
