### ISSUE TITLE
Base URL

### ISSUE THREAD

**Issue by gwenvador** [izderadicka/audioserve#36]
Is there an option to configure the base URL to use audioserve when using a reverse proxy? I can't find one in the configuration.

**Comment by izderadicka** [comment]
No there is no such option, is this needed? Because you can do this also on rev proxy - check for instance #11 for rev proxy discussion.

**Comment by gwenvador** [comment]
On my setup (shared seedbox) I cannot configure how the reverse proxy is configured. I can only points apps to a specific base URL for reverse proxy. It is common settings on other software like radarr/sonarr. If that could be added as an option that would be great for me.

**Comment by izderadicka** [comment]
OK understand - can you pls describe how it should work exactly? What is the problem?

**Comment by gwenvador** [comment]
I have the reverse proxy configuration https://mybox/username/audioserve to http://mybox:3000/username/audioserve
So i need to configure username/audioserve as base URL. So when I connect to the https page it redirects correctly to the web server.

**Comment by izderadicka** [comment]
implemented in [base-url branch](/izderadicka/audioserve/tree/base-url) for now. argument is called `url-path-prefix`.  Can you test?

Also bit more about reverse proxy in [updated README](/izderadicka/audioserve/tree/base-url#reverse-proxy)

**Comment by gwenvador** [comment]
I tried to compile with build_static.sh to test but I have the following error.. Not sure if it is an issue on my side
```
error[E0599]: no method named `strip_prefix` found for type `std::string::String` in the current scope
  --> src/services/mod.rs:58:35
```

Do you have a static compile release?

**Comment by izderadicka** [comment]
This function is in latest stable - do `rustup update` before compilation

**Comment by izderadicka** [comment]
I see in static build script it's fixed to rust version in alpine, will look into it - because version of alpine is also important for correct ffmpeg version

**Comment by izderadicka** [comment]
Replaced strip_prefix, so now current static build script works

**Comment by gwenvador** [comment]
I was able to compile and test the build. It works for me now with the URL prefix. Thank you.

**Comment by izderadicka** [comment]
now moved to master branch and v0.13.0 release
