### ISSUE TITLE
unRAID Template

### ISSUE THREAD

**Issue by TorrnapZ** [izderadicka/audioserve#38]
Any chance of creating an unRAID template and share it to Community Applications?

Or an easy guide to installing it on unRAID.

**Comment by izderadicka** [comment]
In not using unRAID, so only if somebody from community has experiences. Why you not try it yourself?

**Comment by TorrnapZ** [comment]
I have tried but I'm obviously missing something, these are my settings:
https://imgur.com/Pn0UVYi
Which is basically:

"root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='audioserve' --net='bridge' -e TZ="Europe/Berlin" -e HOST_OS="Unraid" -e 'AUDIOSERVE_SHARED_SECRET'='test' -p '3001:4141/tcp' -v '/mnt/user/Media/Books/Audiobooks/':'/audiobooks':'rw' -v '/mnt/user/appdata/audioserve':'/home/audioserve/.audioserve':'rw' 'izderadicka/audioserve'

8e817dd3588fbcda2b9f0545bb2a113a356fb3e440d34bba6dce126f158bd0ce"

But I keep getting these errorcodes in every directory with audiofiles i have:

"Config/Arguments error: Error in config value base_dirs: At least one directory with audio files must be provided"


Any help would be greatly appreciated

**Comment by izderadicka** [comment]
You must provide directory with audio files as parameter -  so in your command you must add /audiobooks as last argument.
