### ISSUE TITLE
Docker Auto-update

### ISSUE THREAD

**Issue by methanoid** [izderadicka/audioserve#39]
Linuxserver.io dockers usually auto update the application contained inside. IF the Audioserve docker does not, could you add that (I'm sure LS.io guys would be happy to help with pointers!)

**Comment by izderadicka** [comment]
I have no plan for this yet.  Not actually even sure if this is good idea - as new versions might require new system dependencies. That why docker was created - right?  To pack all dependencies together - exact linux version, system libraries and app.
