### ISSUE TITLE
Folder Picture

### ISSUE THREAD

**Issue by Homer-Sim** [izderadicka/audioserve#42]
Hello,

I love your so smart but simple server. I am hosting a lot of audio books for my kids. They haven't learned reading so far and I wonder if you could read out of the Folder a picture (jpg file or mp3 meta) and position it before folder name?

Thanks for your effort

**Comment by izderadicka** [comment]
Actually similar request is in #34,  there is no such functionality now.  My design was quite opinionated by my preferences, especially for smaller screens, when I like to have more space for text and omit icons.  It'll require some work on client side mainly (also some work on serve side -  to create a thumbnail of image and store it - if loading of thumbnails should be efficient).

**Comment by Homer-Sim** [comment]
Hello,

I wondered if it would be a good time to raise this request again. 
I am using you great web app for my kids. They are able to listen to audio books with an old tablet but they can not read and it would be a really great improvement to have in front of the list entry a little picture of the folder/file content.

Please reconsider this feature request.

thanks
