### ISSUE TITLE
Feature Request: Log Failed Logins

### ISSUE THREAD

**Issue by andrewrkerr** [izderadicka/audioserve#44]
Request: output failed login attempt with IP and timestamp to a log folder.
Reason: this will allow a user to block an ip for those that expose the server publicly. 

Side note: Thanks for this project! I've tried lots of other options and this one is truly KISS.

**Comment by izderadicka** [comment]
Current log is using env_logger - which by default goes to stderr, but can be redirected to any file. 
I think it could be worth to add bit more error reporting around authentication.

However consider this:   most installations (including mine) are using reverse proxies - so probably more efficient solution for your problem would be to log 401 responses on reverse proxy (there you will see the client addresses and also can add some IP policies there).

**Comment by andrewrkerr** [comment]
Thanks for the quick reply. I'm also using a reverse proxy (NPM), but not using the auth through it. I checked the logs of the reverse proxy, but it's only showing the docker host IP for the client instead of the actual client for the 401 error.

**Comment by izderadicka** [comment]
Implemented in current master branch. 
Basically two things were done:
- all authentication and access failure are logged as error
- added support to access remote ip in request
- and added support to get remote ip from request headers, if behind reverse proxy.

Actually it turnout to be quite interesting problem - thanks to way how hyper works and thanks to possible reverse proxy in between user and audioserve.

If remote/client ip is to be show in log when audioserve is behind reverse proxy more work needs to be done - compile with optional feature behind-proxy  and run with behind-proxy argument.  Reverse proxy must be setup to add either Forwaded or X-Forwarded-For header to passed requests.
