### ISSUE TITLE
Noob question: How to update?

### ISSUE THREAD

**Issue by TheNomad11** [izderadicka/audioserve#45]
I used this command to install audioserve

`docker run -d --name audioserve -p 3000:3000 -e AUDIOSERVE_SHARED_SECRET=mysecret -v /home/myusername/audiobooks:/audiobooks  izderadicka/audioserve  /audiobooks`

How to I update to the newest version? I could not find any documentation. Thanks for your help. I am a noob, still learning Linux and Docker

**Comment by izderadicka** [comment]
Updating audioserve to latest version:

1) Docker
stop current container - `docker stop audioserve` (or whatever name you gave to container during run)
`docker pull izderadicka/audioserve` - to pull latest version of image
or start with `docker run --pull always ..`  (but then with each start you automatically updating to last image)

2) Static build 
Just download latest static build releases and replace

3) Build from source
I guess people will know what to do (git pull or git clone)


I'll keep it open for a while for people  if folks will need some additional support with updating.

**Comment by TheNomad11** [comment]
Thanks a lot, that was easy. When I after` docker pull izderadicka/audioserve`  then use `docker start audioserve` it automatically uses the latest one? How can I double check? Thanks again!

**Comment by izderadicka** [comment]
You can always check version of audioserve in image by running  `docker run --rm izderadicka/audioserve --version`

Re: Edit1 - yes other steps are useful but not  essential, I think - you should need to delete old version of container - but you'll get error if you try to run container with same name. You can use `--rm` to delete container automatically after it is done.

Re: Edit 2:  last remote position - it's bit tricky and probably not exactly bulletproof yet - last position is shared via websocket connection to client.  After restart of server this connection is lost and client tries to reestablish (but it might take time, or maybe client is already had gave up  on retrying)   - so I think easiest is restart client -  but maybe reverse proxy plays some role, I do not know about apache, but I would expect to handle new websocket connection from client if backend is up again.

**Comment by TheNomad11** [comment]
Thanks! It worked fine the way I described it, remote position (from both web version and Android app) included. Generally, position sync has worked very reliably. I have used Audioserve a lot, listening audiobooks and I am very happy with it. Also great that it uses so little resorces. Am running it on the cheapest and slowest VPS that I have and works fine. Thanks so much
