### ISSUE TITLE
Improve security

### ISSUE THREAD

**Issue by izderadicka** [izderadicka/audioserve#46]
Recently I have been thinking bit more about security of audioserve.   And yes I have found one nasty issue (fixed now from v0.15.0) and that motivated me to give more thought to security.

audioserve is not meant to be super secretive, military grade. I'm assuming that people are just streaming audiobooks (or other audio) and that is no big deal, nothing really clandestine. But on the other hand audioserve should be solid and should not allow it's misuse to endanger its hosting system.

So what I have done recently:
- fix bug
- added more information related to security and best practices
- added more detailed logging of authentication failures (including client IP address)
- added wait time after detecting incorrect shared secret - to slow down potential brute force attacks 
- added possibility to limit rate of http requests - to protect system in case of DDoS (also you can solve this on reverse proxy - probably better, but thought it would be nice to have it in audioserve too). BTW number of transcodings (which are most resource intesive) is limited already - from very first version of audioserve.

But I'd like to also get some feedback from users - so please share here:

WHAT ARE YOUR SECURITY ISSUES OR CONCERNS OR QUESTIONS?

(I'll keep this issue opened for while to collect feedback).

**Comment by Knoedelauflauf** [comment]
Thank you for keeping security in mind.
I read your README and this line "Shared secret phrase is never sent in plain (it's sent as salted hash)" got me thinking.
Currently, I don't see any compromise to security, but I also don't see any advantage to doing so. If an adversary can get hold of the PSK's hash, she can send it to the server just as she would if the PSK was compromised.
Commonly the hashing is handled server-side when the user's password is stored or compared, so the server never has to save the plaintext password, but audioserve requires a plaintext PSK.

Do you have any special intend behind client-side hashing?

**Comment by izderadicka** [comment]
@Knoedelauflauf - agree there is not much added value - the only little advantage is if shared secret is used elsewhere (very bad practice indeed, but taking into consideration tons of passwords people have to use and relatively little criticality of audioserve I think people will not spend too much time to create strong unique password for audioserve). 

Also when you change shared secret eavesdropper will not notice, until he will try old one.  Also not much added value, but still nice.

And this scheme can be strengthened  easily (without any change on client) by remembering salts (now 32 bytes) on  server side. 32 bytes is enough to require unique salt for some longer period and thus limit eavesdropping possibility.

Also one other possibility for improvement in this scheme is to use very computationally difficult hash function -   thus limiting possible rate of generated hashes and limit brute force attack.   This is not implemented here, rather  the rate is limited on server side by just waiting with response after failed shared secret check - I felt this is easier then some complex hash function.

**Comment by Knoedelauflauf** [comment]
Thanks for the clarification.
The PSK is also protected if TLS is used correctly. (I would assume TLS is enabled since you have to protect the bearer token).

Do you delay all connections from the same client or only for the connection with the invalid PSK? An attacker could open multiple simultaneous connections.
The rate limit makes brute-force attacks on server access more difficult, i.e. if the PSK/hash is unknown. But if you want to protect the PSK in the hash, the rate limit doesn't increase the difficulty, because an adversary will crack the password offline.

**Comment by izderadicka** [comment]
Yes TLS is indeed essential for security :-) . I think majority of users (including myself) are using reverse proxy for TLS termination. But audioserve provide TLS itself (provided can supply appropriate key + certificates chain) - using openssl library (I was thinking to move sometime to rust-tls - tls implementation in rust, but as audioserve TLS implementation is not much used it is not priority).

There are 3 levels of rate limiting possible:
1.   On reverse proxy -  there (at least from what I've seen in nginx) are much better possibilities for rate limiting that audioserve will ever be able to offer
2. `--limit--rate x`   argument (now in master only not yet tagged for release) -   gives overall rate limit for audioserve -   so no more then app. x requests per second will get through (from any ip).
3. On failed check on shared secret there is delay of 300 ms to respond back (so to be effective in highly concurrent attack should also be combined with rate limiting 1. or 2.).

Re: Offline cracking - yes you're right  - I guess it could be done- here having computationally extensive hash function can help - but I think this is not big issue for audioserve.  It still be quite significant effort with dubious outcome.

**Comment by izderadicka** [comment]
Now I'm looking into web sockets - which are used for position tracking. 
Web sockets are authenticated,  so with good shared secret and TLS there should not be much problems.
However they  represent  sockets/connections opened for long time - so if there are too many of them, they can contribute to file descriptors exhaustion - to start with I'll work  on timeout of inactive web socket connections. 
Again reverse proxy like nginx can help here as it is terminating idle connection.   
It'll require bit more work on clients, so they will be able to recover from websocket arbitrary termination. 
All of this impacts position sharing functionality, which is still considered rather experimental.

**Comment by izderadicka** [comment]
I have done some work  in this area. As I have not see any comments for a while I'll close this issue. If you'll find any real or potential security issue, please report it, thanks.
