### ISSUE TITLE
Feature Request: PWA support

### ISSUE THREAD

**Issue by Only1Thor** [izderadicka/audioserve#49]
It would be great if the page also "exposed" itself as a PWA, so that it could be added as an "app" in IOS, and Android.

**Comment by izderadicka** [comment]
I quickly looked at PWA and there are two main requirement for PWA
1) JSON Manifest 
I think that should be no big deal,  only thing is that some icons should be added to dist resources

2) PWA should load all it's resources via Service Workers 
This is much more problematic - It would probably require bit of redesign of web client. 
Not sure if <audio> tag can work in PWA as it accesses audio resources directly.
Does has anybody experiences with PWA audio application?
I suspect then one will have to dive deep into Cache API and Service Workers and  Web Audio API to make it work properly. On the other hand this can bring advanced caching  and (some) offline capabilities similar to android client.

For now I'm not planing to dive into this.

**Comment by izderadicka** [comment]
Looks like people are just using <audio> element (so no special caching)-  Service worker is used just for loading other resources

https://www.pwabuilder.com

Inspiration :
https://github.com/robinbakker/1tuner
https://github.com/iondrimba/pwa-music-player
https://github.com/arma7x/pwa-audio-player

**Comment by izderadicka** [comment]
@KodeStar - this could be an idea for new web client?

**Comment by KodeStar** [comment]
Yeah, I planned to look into it, will add it to the projects board so I don’t forget

**Comment by KodeStar** [comment]
I have the app running as a PWA, https://audioserve.coderior.com/ but it does bring some of it's own issues.

1. A PWA *must* run on https, which means the server it connects to must also run on https, I've tried running `--ssl-key /audioserve/ssl/audioserve.p12 --ssl-key-password mypass` on the docker install but chrome won't let me connect to it whereas safari is less picky. Unfortunately safari on MacOS doesn't allow you to install a PWA.
2. PWA's on IOS are currently a bit broken where audio is concerned - https://bugs.webkit.org/show_bug.cgi?id=198277 - but hopefully that will be fixed at some point, though running the app not as a PWA *should* work.

**Comment by izderadicka** [comment]
New web client is PWA and is now default client. 
As mentioned above it should be served through trusted https to enable "progressive" features like Service Worker and caching. 
But as recommended by PWA guidelines, basic functionality is available without Service Worker and secure context.
