### ISSUE TITLE
Feature Request: Mark tracks with audio problems

### ISSUE THREAD

**Issue by captbrogers** [izderadicka/audioserve#55]
I completely understand that this may be something that isn't often thought of or needed, but it would be great to be able to mark a track that has audio errors in it such as clicking or popping.

**Comment by izderadicka** [comment]
How such tracks should be detected? If by human, than he can either rename or delete files. If by some automated  process using some audio analysis then again it can rename files. audioserve just shows what is your file system.  This seems to me out of scope for audioserve.
