### ISSUE TITLE
Preflight CORS requests are not hadled correctly

### ISSUE THREAD

**Issue by izderadicka** [izderadicka/audioserve#56]
When using with  `--cors` header and other web client, served from different location then API, and which sends preflight requests , then 
OPTIONS preflight for /authenticate return 401 status, 
thus
client/web browser  cannot access the endpoint

OPTIONS requests handling has to be fixed in audioserve - especially when --cors switch is on.

**Comment by KodeStar** [comment]
@izderadicka https://youtu.be/d3ljM_a0gLA - This is how it currently looks on mobile. It doesn't currently bring the more info panels in on mobile. I'll probably do it so there is a button to show more info if you want and then show the more info panel by default when you get to an actual book, then clicking on the Listen button or clicking on one of the files will open up the player.

**Comment by izderadicka** [comment]
Fix pushed to master

**Comment by izderadicka** [comment]
@KodeStar pls update here if it is working for you.

**Comment by KodeStar** [comment]
I’ve not tried it yet, been busy trying to add features and fix bugs, will try to build from master later today or tomorrow

**Comment by KodeStar** [comment]
Any chance you could put out a release with this change in it? It will be much easier for me to test.

**Comment by izderadicka** [comment]
@KodeStar - released latest master as v0.15.6.  Can you confirm that CORS preflight is now working?

**Comment by KodeStar** [comment]
I think we have a success, it's not complaining about cors any longer, now I just have to work out why what I'm trying to send isn't working :)

**Comment by KodeStar** [comment]
Would it be possible to send the audioserve_token as a custom header instead of a cookie? The issue is, because the server and the frontend aren't on the same address it wont let me set the cookie. So all my subsequent requests to endpoints fail.

**Comment by izderadicka** [comment]
@KodeStar,
Yes you can use Bearer token as well as cookie.   In browser you can you send cookie even to different host (if it was setup by that host).  I'm using it in development of default client (as it is convenient and you don't have manage the header yourself).   Just need to add this option to XHR `withCredentials: true` - see https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials

**Comment by KodeStar** [comment]
I was originally using axios and passing `withCredentials: true` but it didn't help, I have since got rid of axious and am just using fetch, I haven't tried it with that since I got it working by passing the bearer. However, when I tried it with axios I got this error in the browser https://imgur.com/Oa3C4go
```
This attempt to set a cookie via a Set-Cookie header was blocked because it had the "SameSite=Lax" attribute but came from a cross-site response which was not the response to a top-level navigation.
```

**Comment by izderadicka** [comment]
@ Kodestar Hmm, this make sense -  our cookie is now `SameSite: Lax`  so it depends how login is initiated in browser.  Problem is mainly for development, cause normally then client files and API are served from same location in production. 
As I said it works for me now in FF for current client -  probably the way login is initiated suits definition of "top-level navigation".

Anyhow if bearer token working for you it's good solution, as this will in both development and production set up.  If there are still issues with CORS let me know, otherwise I think we can close this issue.

**Comment by KodeStar** [comment]
Agreed :)

**Comment by izderadicka** [comment]
CORS Headers looks working OK.  However still some change needs to be done on cookie - created new issue fo this #64
