### ISSUE TITLE
Mark title/file to download

### ISSUE THREAD

**Issue by DocBrown101** [izderadicka/audioserve#61]
I miss the possibility to download complete files in the app so that I can listen to them without an internet connection.

At the moment, I can only do this by clicking once on all the chapters, which are then downloaded.

**Comment by izderadicka** [comment]
Are we talking about browser client or Android client?
In browser client you can download whole folder - icon on top of files list.
In Android  client swipe left file item - two buttons show up -  one will allow download of all files in the folder - from this one down.
