### ISSUE TITLE
Can't install via Docker

### ISSUE THREAD

**Issue by mariushosting** [izderadicka/audioserve#69]
Error: Config/Arguments error: Error in config value base_dirs: At least one directory with audio files must be provided
I have provided audio directory but the error appears all the time.

**Comment by doc-jay** [comment]
audioserve 0.16.5 #e564aad
Ivan <ivan.zderadicka@gmail.com>

USAGE:
    audioserve [FLAGS] [OPTIONS] [--] [BASE_DIR]...

FLAGS:
        --allow-symlinks             Will follow symbolic/soft links in collections directories
        --behind-proxy               Informs program that it is behind remote proxy, now used only for logging (to get
                                     true remote client ip)
        --cors                       Enable CORS - enabled any origin of requests
    -d, --debug                      Enable debug logging (detailed logging config can be done via RUST_LOG env.
                                     variable)
        --disable-folder-download    Disables API point for downloading whole folder
        --features                   Prints features, with which program is compiled and exits
        --force-cache-update         Forces full reload of metadata cache on start
    -h, --help                       Prints help information
        --help-dir-options           Prints help for collections directories options
        --help-tags                  Prints help for tags options
        --ignore-chapters-meta       Ignore chapters metadata, so files with chapters will not be presented as folders
        --no-authentication          no authentication required - mainly for testing purposes
        --no-dir-collaps             Prevents automatic collaps/skip of directory with single chapterized audio file
        --print-config               Will print current config, with all other options to stdout, useful for creating
                                     config file
        --search-cache               Deprecated: does nothing. For caching config use :<options> on individual
                                     collections dirs params
        --tags                       Collects prefered tags from audiofiles, use argument --help-tags for more details
        --thread-pool-large          Use larger thread pool (usually will not be needed)
    -V, --version                    Prints version information

OPTIONS:
        --chapters-duration <chapters-duration>
            If long files is presented as chapters, one chapter has x mins [default: 30] [env:
            AUDIOSERVE_CHAPTERS_FROM_DURATION=]
        --chapters-from-duration <chapters-from-duration>
            forces split of audio file larger then x mins into chapters (not physically, but it'll be just visible as
            folder with chapters)[default:0 e.g. disabled] [env: AUDIOSERVE_CHAPTERS_FROM_DURATION=]
    -c, --client-dir <client-dir>
            Directory with client files - index.html and bundle.js [env: AUDIOSERVE_CLIENT_DIR=]

    -g, --config <config>
            Configuration file in YAML format [env: AUDIOSERVE_CONFIG=]

        --data-dir <data-dir>
            Base directory for data created by audioserve (caches, state, ...) [default is $HOME/.audioserve] [env:
            AUDIOSERVE_DATA_DIR=]
        --limit-rate <limit-rate>
            Limits number of http request to x req/sec. Assures that resources are not exhausted in case of DDoS (but
            will also limit you). It's bit experimental now. [env: AUDIOSERVE_LIMIT_RATE=]
    -l, --listen <listen>
            Address and port server is listening on as address:port (by default listen on port 3000 on all interfaces)
            [env: AUDIOSERVE_LISTEN=]
        --positions-backup-file <positions-backup-file>
            File to back up last listened positions (can be used to restore positions as well, so has two slightly
            different uses) [default is None] [env: AUDIOSERVE_POSITIONS_BACKUP_FILE=]
        --positions-backup-schedule <positions-backup-schedule>
            Sets regular schedule for backing up playback position - should be cron expression m h dom mon dow- minute
            (m), hour (h), day of month (dom), month (mon) day of week (dow) [env:
            AUDIOSERVE_POSITIONS_BACKUP_SCHEDULE=]
        --positions-restore <positions-restore>
            Restores positions from backup JSON file, value is version of file legacy is before audioserve v0.16,  v1 is
            current [env: AUDIOSERVE_POSITIONS_RESTORE=]  [possible values: legacy, v1]
        --positions-ws-timeout <positions-ws-timeout>
            Timeout in seconds for idle websocket connection use for playback position sharing [default 600s] [env:
            AUDIOSERVE_POSITIONS_WS_TIMEOUT=]
        --secret-file <secret-file>
            Path to file where server secret is kept - it's generated if it does not exists [default: is
            $HOME/.audioserve.secret] [env: AUDIOSERVE_SECRET_FILE=]
    -s, --shared-secret <shared-secret>
            Shared secret for client authentication [env: AUDIOSERVE_SHARED_SECRET=]

        --shared-secret-file <shared-secret-file>
            File containing shared secret, it's slightly safer to read it from file, then provide as command argument
            [env: AUDIOSERVE_SHARED_SECRET_FILE=]
        --ssl-key <ssl-key>
            TLS/SSL private key and certificate in form of PKCS#12 key file, if provided, https is used [env:
            AUDIOSERVE_SSL_KEY=]
        --ssl-key-password <ssl-key-password>
            Password for TLS/SSL private key [env: AUDIOSERVE_SSL_KEY_PASSWORD=]

        --tags-custom <tags-custom>...
            Collects custom tags from audiofiles, list tags searated by comma, use argument --help-tags for more details
            [env: AUDIOSERVE_TAGS_CUSTOM=]
        --thread-pool-keep-alive-secs <thread-pool-keep-alive-secs>
            Threads in pool will shutdown after given seconds, if there is no work. Default is to keep threads forever.
            [env: AUDIOSERVE_THREAD_POOL_KEEP_ALIVE=]
        --token-validity-days <token-validity-days>
            Validity of authentication token issued by this server in days[default 365, min 10] [env:
            AUDIOSERVE_TOKEN_VALIDITY_DAYS=]
    -x, --transcoding-max-parallel-processes <transcoding-max-parallel-processes>
            Maximum number of concurrent transcoding processes [default: 2 * number of cores] [env:
            AUDIOSERVE_MAX_PARALLEL_PROCESSES=]
        --transcoding-max-runtime <transcoding-max-runtime>
            Max duration of transcoding process in hours. If takes longer process is killed. Default is 24h [env:
            AUDIOSERVE_TRANSCODING_MAX_RUNTIME=]
        --url-path-prefix <url-path-prefix>
            Base URL is a fixed path that is before audioserve path part, must start with / and not end with /
            [default: none] [env: AUDIOSERVE_URL_PATH_PREFIX=]

ARGS:
    <BASE_DIR>...    Root directories for audio books, also referred as collections, you can also add :<options>
                     after directory path to change collection behaviour, use --help-dir-options for more details
                     [env: AUDIOSERVE_BASE_DIRS=]

**Comment by mariushosting** [comment]
Unfortunately there is some bugs in the code. After I have tried so many times there is no workaround to make this work on Docker. The docker compose also is not complete.

**Comment by izderadicka** [comment]
Can you share some details:
1) OS , user id , permissions on collection directory ( in container audioserve is running with UID 1000 and it has to have read access to collection dir)
2) which docker image are using
3) Exact command you using to run docker container.

**Comment by mariushosting** [comment]
docker run -d --name=audioserve \
-p 5333:3000 \
-e PUID=1026 \
-e PGID=100 \
-e TZ=Europe/Bucharest \
-e AUDIOSERVE_SHARED_SECRET=password \
-v /volume1/docker/audioserve:/home/audioserve/.audioserve \
-v /volume1/web/music:/audiobooks \
-v /volume1/web/music:/collection1 \
--restart always \
izderadicka/audioserve

**Comment by izderadicka** [comment]
As I did not receive any feedback for a week I assume either previous instructions helped or you are not interested in this issue any more.  For sure audioserve does work in docker, just running as different user/UID requires bit more configuration.
