### ISSUE TITLE
m4b files with slash (/) in chapter name playback error

### ISSUE THREAD

**Issue by player666au** [izderadicka/audioserve#70]
Hi,

 .m4b files with slashes in chapter names are erroring on playback. The error shown in the web interface is:

Player error:
MEDIA_ERR_SRC_NOT_SUPPORTED : Unsupported source type

The web interface shows the chapter name as:

000 - 01 - ...And It Comes Out Here (1/4) (9:57) 24 kbps

The log shows:

[2021-12-05T05:17:27Z ERROR audioserve::services::subs] Requesting non existent file for transcoding Original("/audiobooks/Lester Del Rey/3 Science Fiction Stories by Lester Del Ray (9611)/3 Science Fiction Stories by Lester Del Ra - Lester Del Rey.m4b$$000 - 01 - ...And It Comes Out Here (1")

These types of chapter names are very commonly made with m4b-tool.

Can slashes in chapter names be handled or escaped?

Thanks,

Steve

**Comment by izderadicka** [comment]
Hi,
thanks for logging issue.  
Can you share some problematic m4b file, so I can test it?
I'll need to escape slashes in pseudo path used to identify chapters in m4b.

**Comment by player666au** [comment]
[abk.zip](https://github.com/izderadicka/audioserve/files/7655413/abk.zip)
Thanks for the quick response Ivan.

The attached .zip contains an m4b that errors.

I was getting by with --ignore-chapters-meta in my docker-compose, but that stopped working recently as I think was reported in #69.

Otherwise I must note that this project has been excellent!

Steve

**Comment by izderadicka** [comment]
@player666au 

Hi, problem should be fixed. Tested on your file.   Change is now in master branch and in :unstable image.

Concerning `--ignore-chapters-meta`   -  it does work, but it interferes with cache.   If cache was created without this option, you will see cached results, so it seems, it does not work (cache is updated only if mtime for folder or files within changed).  Fix is simple - just force cache reload -   send USR1 signal to audioserve process -  with docker it should look like this `docker kill -s USR1 audioserve_container`.   (Or modify file on file system,  or stop audioserve and  delete cache, but this will also delete playback positions, so this should be last resort).
Same situation is for couple of other arguments - like `--tags`.  I'll update readme and maybe come up with some improvement in future.

Also you referred #69 / - it is about problem to run docker at all.  Do you have some problems running audioserve in Docker?

**Comment by izderadicka** [comment]
Forgot to mention, there is also `--force-cache-update` argument, which will reload cache on start.

**Comment by player666au** [comment]
Thank you very much Ivan, it's all good now.

Much appreciated.

(Yes, I was aware that the --ignore-chapters-meta setting was cached, and nuked the cache to try to force the desired behaviour. I could have sworn that the :latest docker image ignored that setting. However :unstable definitely follows instructions! and works well)

Also, no I have no problems getting any docker version to run. What finally prompted me to report this issue was the :latest version not following the --ignore-chapters-meta directive any more.

I've just reverted to :latest to check, and the --ignore-chapters-meta option seems to still not be honoured (cache deleted). However, chapters with slashes *are* playing. I have no idea how this is happening!

But now it 'works for me', so I think I'd better be satisfied with your hard work, and close this bug.

Thank you.
