### ISSUE TITLE
Android: Pause on Interruption

### ISSUE THREAD

**Issue by demonspork** [izderadicka/audioserve#71]
Currently in the Android client if an interruption (such as navigation directions) plays, it just gets quieter so you miss a sentence or 2 of the playing audio book. I couldn't find any settings for this, the ideal behavior would be to Pause playback during interruptions.

Bonus would be Android Auto support as well, but that may be a bigger project to implement.

**Comment by izderadicka** [comment]
Could you please log it with audioserve-android as it purely android  client issue, thanks
