### ISSUE TITLE
Allow merging of folders

### ISSUE THREAD

**Issue by Chizi123** [izderadicka/audioserve#76]
I have some of my audiobooks split into folders by CD, but when playing back it would be good to be able to see them as a whole book, rather than seperate.
This also applies to m4a files.

Being able to manually specify that subfolders contain parts of the same book would be useful, if possible.

**Comment by izderadicka** [comment]
Hi,

I do understand folders for CDs, I also do have some folders with CD subfolders - e.g CD0, CD1 etc.  I agree it would be convenient to merge them to one folder.  It'll require 
- a regular expression  to recognize such folder name 
- modification of folder browsing logic a bit -  to go through CD subfolders for given folder and propagate them on level up (what about nested CD like folders -   CD0/CD1 - there should be some logic to handle such cases). 
- maybe prefix/suffix file name with name of CD  folder  - to make i t obvious and distinguish same names, but in different folders.
- also then for live tracking of changes (via inotify events) - the logic will have to be updated. This will be probably most tricky part.

Not sure what you mean by *"This also applies to m4a files."*

*"Being able to manually specify that subfolders contain parts of the same book would be useful, if possible."*
You mean other way of identification of CD subfolder then its name - like having a special file there?  I think name pattern could be enough,.

**Comment by BansheeHero** [comment]
m4a/m4b can contain multiple tracks in one file. So I assume he is talking about having m4a file for each CD separately.
I believe this part is already addressed by dir collapse from my old issue:
https://github.com/izderadicka/audioserve/issues/14

I use foobar to process books before Audioserve and convert CDs into chapters. I believe there should be a way to establish this folder is a book and everything inside should collapse into some form of a chapters. Trigger could regular expression and even something like `.collabsethis` file.

CDs are old and still used. I have met people who still refer to them when talking about a book (Like I just finished CD 1 of Dune)

**Comment by izderadicka** [comment]
For m4a - so we will have an m4a file with chapters metadata only for a part of audiobook  - one CD.

I think having a "tag" file  ".something" in folder  (like proposed  by @BansheeHero)  is good idea - this can force to include all subfolder into current folder - but this has to be limited by subfolders -  more recursion will probably probably make it too complicated unreliable.

As I have written updates of such folders from inotify events can be bit complex.

**Comment by izderadicka** [comment]
Early implementation is in branch collapse-folder. Not all details yet resolved, but basic thing work, with --collapse-cd-folders argument folders matching default regex (like CD1, CD 1 ...) will be merged to parent folder. Also custom regex can be passed via argument --cd-folder-regex.

Feedback is welcomed

**Comment by izderadicka** [comment]
Merging of folders in now in master:
- it's implemented as folder regular expression, having special tag file in folder will be bit too complicated
- also it's implemented only for folders, I have not seen yet .m4b split by CDs. But I do have CD folders in my collection, so I was able to test.
