### ISSUE TITLE
Change document.title to current track name.

### ISSUE THREAD

**Issue by adjenks** [izderadicka/audioserve#81]
When Firefox on Android displays information about the current audio playing, it tells you the name of the tab.
So, it would be useful to see the track name in the title of the page when a song is playing. It could display the application name when nothing is playing.
I think this would be a simple and useful addition.

**Comment by izderadicka** [comment]
Actually modern browser have [MediaSession API](https://developer.mozilla.org/en-US/docs/Web/API/Media_Session_API),  which provides more richer metadata for media playback. 
I'm experimenting with this in [new web client] (https://github.com/izderadicka/audioserve-web/).
Still not ideal, will require more experiments,   support on Android looks bit inconsistent. 
Changing title looks like good idea,   however focus is now on new web client, so it may appear only there.

**Comment by adjenks** [comment]
It's fine if it's done with the MediaSession API 👍
I assumed there was something like that, since I see more advanced controls for other websites in the dropdown menu of my phone, but when I tried to look for something like that but I couldn't find the name of the API.
I guess you just need to set the media meta data on track change. Nice. Looking forward to it. I'll try the new web client when I have time.
