### ISSUE TITLE
iOS and mac decode problems

### ISSUE THREAD

**Issue by ogomez92** [izderadicka/audioserve#86]
Hello,
I'm having issues playing mp3 files on Safari, iOS and mac.

on macOS, it says failed to decode, reload window. And on iOS, it says SRC_NOT_SUPPORTED.
I have the transcoding cache turned on.

Is there any workaround for this?

Thanks.

**Comment by izderadicka** [comment]
read README, there is an section for Apple platforms.
Shortly - Apple does not support opus codec.   
Either do not use transcoding in client,   or change transcoding  on server to aac.

Transcoding cache on server - so you compiled with this feature, right?   For testing different transcodings I'd switch it off, which you can do with program argument when compiled with transcoding cache.

**Comment by ogomez92** [comment]
YEs thanks my bad, I nfigured it out and started using AAC
transcoding. I also turned off the cache. Thanks.

**Comment by izderadicka** [comment]
You could use transcoding cache, if it makes sense for your usecase.   But it depends - usually it makes sense if audioserve is shared by multiple users listening to same files and with same transcoding config on client - then they can share already transcoded and cached files.  For single user it does not make so much sense, as files are also cached in client - unless you are switching frequently between different clients.

**Comment by ogomez92** [comment]
Thanks so much for the explanation.

Yeah, it doesn't make sense for me to use caching (nor transcoding),
since I 1, have high bandwidth and 2, use different clients but one is
Windows, one is mac and the other is iOS, but often it's just
windows/mac.
