### ISSUE TITLE
Add support for m4b single file, large mp3

### ISSUE THREAD

**Issue by izderadicka** [izderadicka/audioserve#9]
One thing that is missing is support for one file audiobooks like m4b (which are now quite popular), large mp3 or aax (which are basically m4b, just encrypted with audible drm) or m4a (same as m4b just different extension).
Idea is to represent such file as a folder,, where containing files will be chapters in the file (or in case where there are no chapters meta just parts of same size, say 30 minutes).
This will require that chapters will be always served through ffmpeg remuxed or transcode to given chapter part only - start time till end time.
The key prerequisite is meta parsing library, that provides chapters meta ( need to look to my livavformat binding).
Best way to represent in API is to extend attributes for folder (to indicate that folder in actually multi chapters file) and for file (indicate that file is actually chapter, it's time offset in the file).

**Comment by izderadicka** [comment]
Support for m4b with chapters meta is in branch chapters

**Comment by izderadicka** [comment]
and now also support for chapterizing large mp3 d64713c033817c11ba3c3fc29c2ecc9cc367a8c0

**Comment by izderadicka** [comment]
Released in v0.9.0 - no support for .aax as they are DRMed.

**Comment by KodeStar** [comment]
Is there no way to serve the streams without transcoding? Or maybe transparently transcode? For example, on the your current web app, if I turn off transcoding, then try to play an m4b I get an error rather than playback.

**Comment by izderadicka** [comment]
For m4b situation is bit special -   as it's displayed and played by chapters, at least some "transcoding"  must take place - actually I call it remuxing - audio stream is not  decoded and encoded, just appropriate time span is cut from the stream and put in the same envelope.

For me it working fine on demo site https://audioserve.zderadicka.eu/ - Bram Stoker - Dracula is m4b.

If you have problem with playing not transcoded m4b, then you might have problem with playing AAC in your browser?  Because if transcoded it'll be then Opus in Ogg container. Try diffrent browser.

**Comment by KodeStar** [comment]
That particular file (the bram stoekr on the demo server) plays for me as well, so it may be something about this particular file, I can send you it if it will help. Again though, if I manually load the file it plays fine in the browser.
