### ISSUE TITLE
ffprobe process

### ISSUE THREAD

**Issue by cnu80** [izderadicka/audioserve#91]
Hi, I am using audioserve on my Synology NAS (docker) . When I start the library scan, many ffprobe processes are started. 

![image](https://user-images.githubusercontent.com/28894450/212002969-cf052fe6-a018-4aff-ab20-366624d3b274.png)
![image](https://user-images.githubusercontent.com/28894450/212003078-b769abd4-a893-4491-aca4-af2b4a5cf7d4.png)

Is there a way to limit the count? thanks

**Comment by cnu80** [comment]
Sorry false project

**Comment by izderadicka** [comment]
@cnu80  NP - was bit confused as audioserve is not using ffprobe
