### ISSUE TITLE
Artificially Low Limit on File Name Length

### ISSUE THREAD

**Issue by OrangeDrangon** [izderadicka/audioserve#96]
I have recently ran into a book triggering the Chapter name too long error. I manually bumped the if condition in the collections/audio_folder.rs file and it seems to be working now. Is there any chance this limit could be bumped upstream?

**Comment by izderadicka** [comment]
Where exactly is this condition - line no?
Or ideally PR.   
Thanks

**Comment by OrangeDrangon** [comment]
Ok so I cannot be 100% of correctness for the change. I was testing with an m4b file which does not store the chapters as real files and therefore would not be running into the NAME_MAX constant present in most file systems. I think any change would need to know if the chapter would actually be going to disk or not.

The relevant line is crates/collection/src/audio_folder.rs:667

In my testing with an m4b file I ran into no errors with super long chapter names. I am unsure what happens when run with chapters that are actual fiiles (mp3 files).

**Comment by izderadicka** [comment]
Hi,
this limit is only for chapters from metadata, e.g. mostly for m4b (but mp3 can also have chapters).  Rather then increasing size I thing I'll cut the chapter name (probably somewhere in middle).  Good thing is that chapter names does not have to be unique, as they are already identified uniquely by time offset in the file.

Reason for cutting the length is twofold:
- first for client usability - too long chapter names will make problems in client file/chapter browsers, so it'll need to be cut anyhow,
- second - file/chapter names are used as keys in collection cache - having too big keys there will not be efficient

@OrangeDrangon Will this solution work for you?

**Comment by OrangeDrangon** [comment]
Sounds reasonable.

**Comment by izderadicka** [comment]
Fix applied to current master branch and thus to unstable image.
