### ISSUE TITLE
[ Feature Request ] package this as a Start9 Service

### ISSUE THREAD

**Issue by PlebeiusGaragicus** [izderadicka/audioserve#97]
I think this would make a great addition to the new category of self-hosted software that runs on home (read: Bitcoin) nodes.

Having an official .s9pk release would make it simple to start using.

I'd love to take on the challenge of [packaging this](https://docs.start9.com/latest/developer-docs/) myself.

**Comment by izderadicka** [comment]
NP go ahead. Docker image is available. I myself have no interest in Start9, but will accept  PR, if it will not infer with other functionality/packing

**Comment by izderadicka** [comment]
I do not have access to Start9 and nobody tool over this issues, I'll close.  Still open for PR if it'll come in future.
